version : '3.6'
services :
  db :
    build :
      context : "."
      dockerfile : "Dockerfile-postgre"
    ports :
      - "5423:5432"
  api :
    links :
      - db
    build : 
      context : "."
      dockerfile : "Dockerfile-go"
    ports :
      - "8080:80"
    environment :
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tn_task
      - DB_SCHEMA=public
      - MAIL_USER=ruly.devs@gmail.com
      - MAIL_PASSWORD=sapayangtua
      - MAIL_SMTP=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SENDER=ruli
      - APP_NAME=tn-test
      - APP_VERSION=1.0.0
  