FROM postgres:10-alpine

RUN apk add tzdata &&\
    cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime &&\
    echo "Asia/Jakarta" > /etc/timezone &&\
    apk del tzdata

ENV POSTGRES_DB tn_task
ADD TN_DB_DDL.sql /docker-entrypoint-initdb.d/
CMD [ "postgres" ]